### PR TITLE
[wip-ish] Index fixes & refactoring

### PR DESCRIPTION
**Pull request by alberth**
Fixes out-of bounds access to the buffer, and full usage of all buffer positions.
Also did some refactoring and documenting

Code should be done, but I don't have a compiler setup nearby currently to check.

### CODE REVIEW

**Comment by LoyVanBeek** [comment]
> Code should be done, but I don't have a compiler setup nearby currently to check.
@alberth Can you set up Travis CI to run the compiler?

**Comment by alberth** [comment]
@LoyVanBeek  Added a travis file from emergency_speakup, which seems to be generic.
Lilkely the repo needs some configuring too, but I can't do that I think, as I can't even push a branch to it.

**Comment by reinzor** [comment]
The .travis file will most probably not work since the matrix libs are not available. I will test this next Tuesday, thanks :)

**Comment by LoyVanBeek** [comment]
@alberth I changed the permissions for this repo to be the same as the other repos.

**Comment by MatthijsBurgh** [comment]
Next to the matrix libs being not available. The added travis config is for repos for which the main folder also a ros pacakge is. https://github.com/tue-robotics/tue_robocup/blob/master/.travis.yml shows a config for the subfolder being ros packages.

**Comment by MatthijsBurgh** [comment]
Tested on AMIGO. No memory allocation errors anymore.

**Pull request merged**
